import { Inter, Outfit } from 'next/font/google'
import './globals.css'
import Header from './_components/Header'
import Hero from './_components/Hero'

const inter = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Hero/>
        {children}
      </body>
    </html>
  )
}
